baseurl = "http://joshwerts.com"
languageCode = "en-us"
title = "Josh Werts"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
disqusShortname = "jwerts"
theme = "steam-josh"

# color-codes for highlighting derived from this style
pygmentsStyle = "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses = false

[permalinks]
    post = "/blog/:year/:month/:day/:title/"



[params]
    name = "Josh Werts"
    bio = "<br/><strong>Senior GIS Software Developer working remotely from Boone, NC for Patrick Engineering.</strong><br/><br/>I enjoy working with open source technologies though I’m highly proficient in all things ESRI. I prefer to work in multiple languages and constantly learn new ones, but my day to day work is typically full-stack web development in JavaScript, Python, and C#. I’m searching for a project to learn Go!"
    title = "Josh Werts"
    subtitle = "{ 'work': ['gis', 'py', 'js' ...], 'fun': ['bike', 'hike', 'paddle', ...] }"
    description = "some lines of code..."
    location = "Boone, NC"
    mapLatLong = "36.216795,-81.674552"
    copyright = "All Rights Reserved"

    # You can choose between green, orange, red and blue.
  	themeColor = "blue"

  	# Enable Google Analytics be inserting your tracking code
  	googleAnalytics = "UA-49518677-1"

    github = "jwerts"
    instagram = "joshwerts"

    comments = "disqus"
    keepReadingStr = "More..."
    backtotopStr = "Back to top"
    shareStr = "Share"
    pageNotFoundTitle = "404 - Couldn't find this page!"
